### ISSUE TITLE
Archive on plugins contains duplicated xlswriter

### ISSUE THREAD

**Issue by jef-n** [BergWerkGIS/VoGIS-Profil-Tool#11]
The uploaded archive on http://plugins.qgis.org/plugins/VoGisProfilTool/version/2.99.1/download/ has `util/xlsxwriter` and a leftover toplevel `xlsxwriter`, which produces here:

```
Konnte Erweiterung 'VoGisProfilTool' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

AttributeError: module 'VoGisProfilTool' has no attribute 'util' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/jef.NORBIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VoGisProfilTool\__init__.py", line 26, in classFactory
    from VoGisProfilTool.vogisprofiltoolmain import VoGISProfilToolMain
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/jef.NORBIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VoGisProfilTool\vogisprofiltoolmain.py", line 31, in 
    from VoGisProfilTool.vogisprofiltoolmaindialog import VoGISProfilToolMainDialog
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/jef.NORBIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VoGisProfilTool\vogisprofiltoolmaindialog.py", line 34, in 
    from VoGisProfilTool.vogisprofiltoolplot import VoGISProfilToolPlotDialog
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/jef.NORBIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VoGisProfilTool\vogisprofiltoolplot.py", line 56, in 
    from VoGisProfilTool.util.exportXls import ExportXls
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/jef.NORBIT/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\VoGisProfilTool\util\exportXls.py", line 3, in 
    import VoGisProfilTool.util.xlsxwriter as xlsxwriter
AttributeError: module 'VoGisProfilTool' has no attribute 'util'
```

**Comment by BergWerkGIS** [comment]
Thanks @jef-n 
Should be fixed in upcoming release.
